application:
  phase: LOCAL

server:
  error:
    includeStacktrace: ALWAYS

spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          connection-timeout: 30000
          socket-timeout: 30000
  elasticsearch:
    rest:
      uris: http://localhost:9200

auth:
  userCache:
    maximumSize: 1000
    expireAfterWriteMinutes: 10
  httpClient:
    baseUrl: http://coffeeshop-auth-service.domain.com
    connectTimeoutMillis: 5000
    readTimeoutSec: 5
    writeTimeoutSec: 5
    soKeepAlive: true
    tcpNoDelay: true
    reuseAddr: true

menu:
  search:
    vectorScoring: true


debug: true
